apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: athl0n/tiqzy-cms:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "https://api.tiqzyapi.nl"
            - name: COREPACK_HOME
              value: "/tmp/corepack"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  selector:
    app: cms
  ports:
    - name: port-80
      protocol: TCP
      port: 80
      targetPort: 80
