name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build-vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'The7Guys'
          reponame: 'Tiqzy.CMS'
          token: ${{ secrets.GITHUB_TOKEN }} 

